
services:

  mediamtx:
    image: bluenviron/mediamtx
    ports:
      - 1935:1935
      - 8554:8554
      - 8888:8888
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CHANGE_ME_12345!

  website:
    hostname: SecurityWebsite
    build: ./SecurityWebSite
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./cert
        target: /app/cert
